name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH key and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_ADDRESS }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AWS_EC2_USER }}/DJBuddy_Backend
            git pull origin main
            sudo systemctl restart nginx
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install httpx pytest

      - name: Run tests
        run: |
          pytest -v
          test_result=$?
          if [ $test_result -ne 0 ]; then
            echo "Tests failed. Exiting with code $test_result"
            exit 1  # Explicitly mark the job as failed
          fi
